### ISSUE TITLE
Settings are not updated

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/element-index-defaults#6]
**Description**
When we save the settings, it is not saved correctly. It is not overwritten by the config file (we deleted this because we thought this was the issue).

**Steps to reproduce**
1. Change the table column in the settings /admin/element-index-defaults/settings
2. Save the settings
3. The old settings are saved

**Additional info**
- Plugin version: 2.0.0
- Craft version: 3.7.16
- Multi-site: No

**Additional context**
Original settings:
![Screenshot 2021-10-12 at 11 54 49](https://user-images.githubusercontent.com/42932673/136934925-c1f9b5ca-a948-4f5f-9fea-c951f44d1034.png)
We changed the settings:
![Screenshot 2021-10-12 at 11 55 28](https://user-images.githubusercontent.com/42932673/136934945-49042a78-6e75-45e3-bb6f-fc98223d14cb.png)
Plugin is saved and settings are back to old values:
![Screenshot 2021-10-12 at 11 55 08](https://user-images.githubusercontent.com/42932673/136934950-74835b3f-88ee-4ed8-ab3b-e32ee19417cc.png)

**Comment by engram-design** [comment]
The config settings should certainly be overriding things.

The default Entry settings
![image](https://user-images.githubusercontent.com/1221575/137051948-b68e4ec0-3e35-470b-9f8e-88012ec61d16.png)

Including the following in `config/element-index-defaults.php`

```php
<?php
use craft\elements\Entry;

return [
    '*' => [
        'elementDefaults' => [
            Entry::class => [
                'slug',
            ],
        ],
    ]
];
```

Produces:

![image](https://user-images.githubusercontent.com/1221575/137052043-038c16d0-6a5c-4560-acba-60800ab3725f.png)

However I can see the issue with saving values not persisting. Please note the breaking change in 2.0.0 with regards to your config file - https://github.com/verbb/element-index-defaults#configuration-file

Should be fixed in [2.0.1](https://github.com/verbb/element-index-defaults/releases/tag/2.0.1)
